./Config -quick did not run "make clean" automatically.
It is important that "make clean" gets run after running ./Config
because otherwise only a partial (or no) recompile might happen
if the user does not type that themselves.

This was working for ./Config but not ./Config -quick because the
setting of $MAKE (if empty) only happened in the non-quick code.

diff --git a/Config b/Config
--- a/Config
+++ b/Config
@@ -300,6 +300,31 @@ else
 	n="-n"
 fi
 
+# Check for gmake early (and set $MAKE if empty, as we need it later)..
+if [ "$MAKE" = "" ]; then
+	MAKE="make"
+fi
+if ! $MAKE --version 2>&1|grep -q "GNU Make"; then
+	# So $MAKE is not GNU make, but do we have gmake?
+	if gmake --version 2>&1|grep -q "GNU Make"; then
+		# Great, use that one!
+		MAKE="gmake"
+	else
+		# Both $MAKE and gmake are not GNU make, do we have a working $MAKE at all?
+		if command -v "$MAKE" 1>/dev/null 2>&1; then
+			echo "Your system has 'make' but UnrealIRCd requires GNU Make ('gmake')"
+			echo "Please install 'gmake' "
+			echo "eg 'pkg install gmake' on FreeBSD and 'pkg_add gmake' on OpenBSD."
+			exit 1
+		else
+			echo "Your system does not have the required tools installed to build UnrealIRCd."
+			echo "Please check https://www.unrealircd.org/docs/Installing_from_source"
+			echo "and install the required tools listed under 'Prerequisites'."
+			echo "After that, you can run ./Config again"
+			exit 1
+		fi
+	fi
+fi
 
 #parse arguments
 IMPORTEDSETTINGS=""
@@ -346,34 +371,6 @@ if [ "`id -u`" = "0" ]; then
 	echo "See https://www.unrealircd.org/docs/Do_not_run_as_root"
 	exit
 fi
-
-# Check for gmake early...
-if [ "$MAKE" = "" ]; then
-	MAKE="make"
-fi
-
-if ! $MAKE --version 2>&1|grep -q "GNU Make"; then
-	# So $MAKE is not GNU make, but do we have gmake?
-	if gmake --version 2>&1|grep -q "GNU Make"; then
-		# Great, use that one!
-		MAKE="gmake"
-	else
-		# Both $MAKE and gmake are not GNU make, do we have a working $MAKE at all?
-		if command -v "$MAKE" 1>/dev/null 2>&1; then
-			echo "Your system has 'make' but UnrealIRCd requires GNU Make ('gmake')"
-			echo "Please install 'gmake' "
-			echo "eg 'pkg install gmake' on FreeBSD and 'pkg_add gmake' on OpenBSD."
-			exit 1
-		else
-			echo "Your system does not have the required tools installed to build UnrealIRCd."
-			echo "Please check https://www.unrealircd.org/docs/Installing_from_source"
-			echo "and install the required tools listed under 'Prerequisites'."
-			echo "After that, you can run ./Config again"
-			exit 1
-		fi
-	fi
-fi
-
 
 clear
 
