- c-ares (currently, a forked off version) enhancements:   - '/quote dns i' now shows the nameserver settings (which is taken from /etc/resolv.conf     on *NIX, and from the registry on Windows)   - We no longer depend on a C++ compiler (was useless c-ares dependency caused by libtool)   - '/REHASH -dns' now rereads the resolver data from resolv.conf/registry, no IRCd restart     needed anymore. It's currently kinda experimental however, but I *think* it will work ok.   Unfortunately the above features required some ugly hacks if curl was enabled, so if you   use curl (Remote includes), feel free to test on your OS (Linux, but especially FreeBSD   and the other *NIXes) to see if things still compile (make clean; ./Config && make).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12143,13 +12143,19 @@ if test "${enable_libcurl+set}" = set; then
   enableval="$enable_libcurl"
 
 		CURLCFLAG=`$enableval/bin/curl-config --cflags`
-		CFLAGS="$CFLAGS $CURLCFLAG -DUSE_LIBCURL"
 		CURLLIBS=`$enableval/bin/curl-config --libs`
 
-				if test "x`echo $CURLLIBS |grep .*ares.*`" = x ; then
-			CURLLIBS="$CURLLIBS -lares"
+														if test "x`echo $CURLLIBS |grep ares`" != x ; then
+			CURLLIBS="`echo "$CURLLIBS"|sed -r 's/([^ ]+ [^ ]+ )([^ ]+ [^ ]+ )(.+)/\1\3/g'`"
+			if test x"$CURLLIBS" = x; then
+				{ { echo "$as_me:$LINENO: error: sed appears to be broken. It is needed for a remote includes compile hack." >&5
+echo "$as_me: error: sed appears to be broken. It is needed for a remote includes compile hack." >&2;}
+   { (exit 1); exit 1; }; }
+			fi
 		fi
+
 		IRCDLIBS="$IRCDLIBS $CURLLIBS"
+		CFLAGS="$CFLAGS $CURLCFLAG -DUSE_LIBCURL"
 		URL="url.o"
 
 
