Made Unreal use FSU Pthreads if the system has 'broken' pthreads

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3589,7 +3589,7 @@ fi
 if test "${enable_ssl+set}" = set; then
   enableval="$enable_ssl"
   
-if test $openssl = yes; then
+if test "$openssl" = "yes"; then
 cat >> confdefs.h <<\EOF
 #define USE_SSL 1
 EOF
@@ -4100,6 +4100,70 @@ fi
 else
         PTHREAD_CC="$CC"
 fi
+if test "x$ac_cv_pthreadflag"!=x; then
+echo $ac_n "checking if pthreads uses one thread per process""... $ac_c" 1>&6
+echo "configure:4106: checking if pthreads uses one thread per process" >&5
+if eval "test \"`echo '$''{'ac_cv_thread_multi'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+save_LIBS="$LIBS"
+LIBS="$PTHREAD_LIBS $LIBS"
+save_CFLAGS="$CFLAGS"
+CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 4119 "configure"
+#include "confdefs.h"
+
+#include <pthread.h>
+int pid;
+void testthreads() {
+if (getpid() == pid)
+	exit(0);
+exit(1);
+}
+int main() {
+pthread_t thread;
+pthread_attr_t attrs;
+pid = getpid();
+pthread_attr_init(&attrs);
+pthread_create(&thread, &attrs, (void*)testthreads, NULL);
+while (1);
+}
+
+EOF
+if { (eval echo configure:4139: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  ac_cv_thread_multi=no
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  ac_cv_thread_multi=yes
+fi
+rm -fr conftest*
+fi
+
+LIBS="$save_LIBS"
+CFLAGS="$save_CFLAGS"
+
+fi
+
+echo "$ac_t""$ac_cv_thread_multi" 1>&6
+if test "$ac_cv_thread_multi" = "yes"; then
+echo "$ac_t""Ok we'll install FSU Pthreads" 1>&6
+cd extras
+tar xfz pthreads.tar.gz
+cd threads/src
+./configure
+cd ../../../
+PTHREAD_CFLAGS="-I=../extras/threads/include $ac_cv_pthreadspecial"
+PTHREAD_LIBS="../extras/lib/libgthreads.a ../extras/lib/libmalloc.a"
+fi
+fi
 
 
 
@@ -4122,12 +4186,12 @@ CC="$PTHREAD_CC"
 CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
 IRCDLIBS="$IRCDLIBS $PTHREAD_LIBS"
 echo $ac_n "checking if FD_SETSIZE is large enough to allow $ac_fd file descriptors""... $ac_c" 1>&6
-echo "configure:4126: checking if FD_SETSIZE is large enough to allow $ac_fd file descriptors" >&5
+echo "configure:4190: checking if FD_SETSIZE is large enough to allow $ac_fd file descriptors" >&5
 if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 4131 "configure"
+#line 4195 "configure"
 #include "confdefs.h"
 
 #include <sys/types.h>
@@ -4139,7 +4203,7 @@ exit(1);
 }
 
 EOF
-if { (eval echo configure:4143: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:4207: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   echo "$ac_t""yes" 1>&6
 else
