We already checked for the openssl library but if the openssl binary was not found then this was not treated as a fatal error. Now it is, since you will fail later in the installation process when a certificate file is being made (resulting in mysterious 'req: command not found' errors). Also, improve the error message both for the missing openssl library and openssl binary case.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2754,6 +2754,19 @@ $as_echo "no" >&6; }
 fi
 
 
+if test x"$OPENSSLPATH" = "x"; then :
+
+echo ""
+echo "Apparently you do not have both the openssl binary and openssl development libraries installed."
+echo "The following packages are required:"
+echo "1) The library package is often called 'openssl-dev', 'openssl-devel' or 'libssl-dev'"
+echo "2) The binary package is usually called 'openssl'."
+echo "NOTE: you or your system administrator needs to install the library AND the binary package."
+echo "After doing so, simply re-run ./Config"
+exit 1
+
+fi
+
 # Extract the first word of "install", so it can be a program name with args.
 set dummy install; ac_word=$2
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
@@ -8529,9 +8542,11 @@ $as_echo "found in $ssldir/include" >&6; }
 $as_echo "not found" >&6; }
 		echo ""
 		echo "Apparently you do not have both the openssl binary and openssl development libraries installed."
-		echo "Please install the needed binaries and libraries."
-		echo "The package is often called 'openssl-dev', 'openssl-devel' or 'libssl-dev'"
-		echo "After doing so re-run ./Config"
+		echo "The following packages are required:"
+		echo "1) The library package is often called 'openssl-dev', 'openssl-devel' or 'libssl-dev'"
+		echo "2) The binary package is usually called 'openssl'."
+		echo "NOTE: you or your system administrator needs to install the library AND the binary package."
+		echo "After doing so, simply re-run ./Config"
 		exit 1
 	else
 		CRYPTOLIB="-lssl -lcrypto";
