Improve (error) messages shown on console while booting. Fatal boot errors are now shown on the console, no need to check ircd.log.

diff --git a/unrealircd.in b/unrealircd.in
--- a/unrealircd.in
+++ b/unrealircd.in
@@ -26,17 +26,24 @@ if [ "$1" = "start" ] ; then
 		echo "See https://www.unrealircd.org/docs/UnrealIRCd_files_and_directories"
 		exit 1
 	fi
+	if [ ! -f @CONFDIR@/unrealircd.conf ]; then
+		echo ""
+		echo "The configuration file does not exist (@CONFDIR@/unrealircd.conf)."
+		echo "* Create one by following:"
+		echo "  https://www.unrealircd.org/docs/Installing_from_source#Creating_a_configuration_file"
+		echo "* Or if you are upgrading from version 3.2.x then read:"
+		echo "  https://www.unrealircd.org/docs/Upgrading_from_3.2.x and"
+		echo "  https://www.unrealircd.org/docs/UnrealIRCd_files_and_directories"
+		exit 1
+	fi
 	@BINDIR@/unrealircd
-	sleep 1
-	if [ ! -r $PID_FILE ] ; then
-		echo "Possible error encountered (IRCd seemingly not started)"	
+	if [ $? -ne 0 ] ; then
 		echo "====================================================="
-		echo "Check above for possible errors and the output below of @LOGDIR@/ircd.log"
+		echo "UnrealIRCd failed to start. Check above for possible errors."
 		echo "If you don't understand the problem, then have a look at our:"
-		echo "* FAQ: https://www.unrealircd.org/faq (Frequently Asked Questions)"
+		echo "* FAQ (Frequently Asked Questions): https://www.unrealircd.org/docs/FAQ"
 		echo "* Documentation: https://www.unrealircd.org/docs/"
 		echo "====================================================="
-		tail -n 5 @LOGDIR@/ircd.log
 		if [ -r $PID_BACKUP ] ; then
 			mv -f $PID_BACKUP $PID_FILE
 		fi
