Add './unrealircd reloadtls' to reload SSL/TLS certificates and keys. Suggested by Bob_Sheep (#4537) to aid the usage of Let's Encrypt. Note that this is the same as doing '/REHASH -ssl' on IRC.

diff --git a/unrealircd.in b/unrealircd.in
--- a/unrealircd.in
+++ b/unrealircd.in
@@ -100,6 +100,17 @@ elif [ "$1" = "croncheck" ] ; then
 	# PID file not found or found but stale
 	echo "UnrealIRCd is not running. Starting now..."
 	$0 start
+elif [ "$1" = "reloadtls" ] ; then
+	echo "Reloading SSL/TLS certificates"
+	if [ ! -r $PID_FILE ] ; then
+		echo "ERROR: UnrealIRCd is not running"
+		exit 1
+	fi
+	kill -USR1 `cat $PID_FILE`
+	if [ "$?" != 0 ]; then
+		echo "ERROR: UnrealIRCd is not running"
+		exit 1
+	fi
 elif [ "$1" = "mkpasswd" ] ; then
 	@BINDIR@/unrealircd -P $2 $3
 elif [ "$1" = "version" ] ; then
@@ -193,5 +204,5 @@ __EOF__
 	echo ""
 	echo "Thanks!"
 else
-	echo "Usage: unrealircd start|stop|rehash|restart|mkpasswd|version|croncheck|gencloak|upgrade-conf"
+	echo "Usage: unrealircd start|stop|rehash|restart|mkpasswd|version|croncheck|gencloak|reloadtls|upgrade-conf"
 fi
