unrealircd script: * detect "ircd not running" situations better * ./unrealircd stop now kills the ircd in a more friendly matter. * if you run './unrealircd restart' it will now also start the ircd even if it was not presently running.

diff --git a/unrealircd.in b/unrealircd.in
--- a/unrealircd.in
+++ b/unrealircd.in
@@ -35,7 +35,13 @@ elif [ "$1" = "stop" ] ; then
 		echo "ERROR: UnrealIRCd is not running"
 		exit 1
 	fi
-	kill -9 `cat $PID_FILE`
+	kill -15 `cat $PID_FILE`
+	if [ "$?" != 0 ]; then
+		echo "ERROR: UnrealIRCd is not running"
+		exit 1
+	fi
+	sleep 1
+	kill -9 `cat $PID_FILE` 1>/dev/null 2>&1
 elif [ "$1" = "rehash" ] ; then
 	echo "Rehashing UnrealIRCd"
 	if [ ! -r $PID_FILE ] ; then
@@ -43,13 +49,24 @@ elif [ "$1" = "rehash" ] ; then
 		exit 1
 	fi
 	kill -1 `cat $PID_FILE`
-elif [ "$1" = "restart" ] ; then
-	echo "Restarting UnrealIRCd"
-	if [ ! -r $PID_FILE ] ; then
+	if [ "$?" != 0 ]; then
 		echo "ERROR: UnrealIRCd is not running"
 		exit 1
 	fi
-	kill -2 `cat $PID_FILE`
+elif [ "$1" = "restart" ] ; then
+	echo "Restarting UnrealIRCd"
+	if [ ! -r $PID_FILE ] ; then
+		echo "WARNING: UnrealIRCd was not running"
+	else
+		kill -15 `cat $PID_FILE`
+		if [ "$?" != 0 ]; then
+			echo "WARNING: UnrealIRCd was not running"
+		else
+			sleep 1
+			kill -9 `cat $PID_FILE` 1>/dev/null 2>&1
+		fi
+	fi
+	$0 start
 elif [ "$1" = "mkpasswd" ] ; then
 	@BINDIR@/unrealircd -P $2 $3
 elif [ "$1" = "version" ] ; then
