Don't test w/services on FreeBSD since it errors mysteriously atm.

diff --git a/extras/build-tests/nix/run-tests b/extras/build-tests/nix/run-tests
--- a/extras/build-tests/nix/run-tests
+++ b/extras/build-tests/nix/run-tests
@@ -24,8 +24,14 @@ git clone -q https://github.com/unrealircd/unrealircd-tests.git
 cd unrealircd-tests
 
 # Run the test framework, testing both services:
-./run -services anope || exit 1
-./run -services atheme || exit 1
+if uname -a|grep -q FreeBSD; then
+	# FreeBSD runs without services since they fail mysteriously:
+	./run -services none || exit 1
+else
+	# Linux tests both with anope and atheme services:
+	./run -services anope || exit 1
+	./run -services atheme || exit 1
+fi
 
 # Do cipherscan test at the end
 if [[ "$OSTYPE" != "freebsd"* ]]; then
